services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

    h4a.command.updatePlayerscores:
        class: Janborg\H4aGamestats\Command\UpdateH4aScoresCommand
        arguments:
            - '@contao.framework'
        tags: 
            - "console.command"