services:
    _defaults:
        autoconfigure: true
        autowire: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - [setFramework, ['@contao.framework']]

    h4agamestats.content.options.callback:
        class: Janborg\H4aGamestats\EventListener\DataContainer\ContentListener   
        arguments:
            - '@contao.framework'
            - '@database_connection'

    Janborg\H4aGamestats\EventListener\DataContainer\UnsetH4aGamestatsOperationCallback: ~