services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - ['setContainer', ['@Psr\Container\ContainerInterface']]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ['setContainer', ['@service_container']]

    Janborg\H4aGamestats\Controller\ContentElement\H4aGameScoreElement: ~

    Janborg\H4aGamestats\Controller\ContentElement\H4aSeasonScoreElement: ~

    Janborg\H4aGamestats\Controller\ContentElement\H4aTimelineElement: ~

    Janborg\H4aGamestats\Controller\FrontendModule\H4aEventReportController: ~
    
    Janborg\H4aGamestats\Cron\UpdateH4aScoresCron:
        arguments:
            - '@contao.framework'
        tags:
            -
                name: contao.cronjob
                interval: 'hourly'
                method: updateScores