services:
    _defaults:
        autoconfigure: true
        public: true
        autowire: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - ['setContainer', ['@Psr\Container\ContainerInterface']]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ['setContainer', ['@service_container']]

    Janborg\H4aGamestats\H4aEventGamestats: ~

    Janborg\H4aGamestats\Controller\:
        resource: '../../Controller/*'

    Janborg\H4aGamestats\Cron\UpdateH4aScoresCron:
        arguments:
            - '@contao.framework'
        tags:
            -
                name: contao.cronjob
                interval: 'hourly'
                method: updateScores
    
