services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

    h4a.command.updatePlayerscores:
        class: Janborg\H4aGamestats\Command\UpdateH4aScoresCommand
        arguments:
            - '@contao.framework'
            - '@contao.cache.entity_tags'
            - '@h4atabellen.h4aapihelper'
        tags: 
            - "console.command"

    h4a.command.updateTimeline:
        class: Janborg\H4aGamestats\Command\UpdateH4aTimelineCommand
        arguments:
            - '@contao.framework'
            - '@contao.cache.entity_tags'
            - '@h4atabellen.h4aapihelper'
        tags: 
            - "console.command"