services:
    _defaults:
        autoconfigure: true
        autowire: true

    Janborg\H4aGamestats\Controller\:
        resource: '../src/Controller/*'
        
    Janborg\H4aGamestats\Backend\LookupScoresController:
        public: true
        arguments: 
            - '@contao.cache.entity_tags'
            - '@h4agamestats.crawler.gamestatscrawler'
            - '@monolog.logger.contao.error'

    Janborg\H4aGamestats\Backend\LookupTimelineController:
        public: true
        arguments: 
            - '@contao.cache.entity_tags'
            - '@h4agamestats.crawler.gamestatscrawler'
