services:
    _defaults:
        autoconfigure: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

    janborg.h4agamestats.migration.playerscores:
        class: Janborg\H4aGamestats\Migration\WronglyEncodedPlayerscoresMigration
        arguments:
            - "@database_connection"
            - "@contao.framework"
            - "@contao.cache.entity_tags"

    janborg.h4agamestats.migration.timelines:
        class: Janborg\H4aGamestats\Migration\WronglyEncodedTimelinesMigration
        arguments:
            - "@database_connection"
            - "@contao.framework"
            - "@contao.cache.entity_tags"
