services:
    _defaults:
        autoconfigure: true
        public: true
        autowire: true

    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ['setFramework', ['@contao.framework']]

        Symfony\Bundle\FrameworkBundle\Controller\AbstractController:
            calls:
                - ['setContainer', ['@Psr\Container\ContainerInterface']]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ['setContainer', ['@service_container']]

    Janborg\H4aGamestats\H4aEventGamestats: ~

    h4agamestats.cron.updatescores:
        class: Janborg\H4aGamestats\Cron\UpdateH4aScoresCron
        arguments:
            - '@contao.framework'
            - '@contao.cache.entity_tags'
            - '@monolog.logger.contao.cron'
            - '@h4agamestats.crawler.gamestatscrawler'
        tags:
            -
                name: contao.cronjob
                interval: 'hourly'
                method: updateScores
                priority: -50
    
    h4agamestats.cron.updatetimeline:
        class: Janborg\H4aGamestats\Cron\UpdateH4aTimelineCron
        arguments:
            - '@contao.framework'
            - '@contao.cache.entity_tags'
            - '@monolog.logger.contao.cron'
            - '@h4agamestats.crawler.gamestatscrawler'
        tags:
            -
                name: contao.cronjob
                interval: 'hourly'
                method: updateTimeline
                priority: -100
    
    h4agamestats.crawler.gamestatscrawler:
        class: Janborg\H4aGamestats\Crawler\GameStatsCrawler
        public: true

